name: Bloggy CD
on:
    push:
        branches: ['main']
jobs:
    build-and-push:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        env:
            IMAGE_NAME: runipanda/blog-app
            IMAGE_TAG: build-${{github.sha}} #runipanda/blog-app:build-1
        steps:
            - name: Checkout the source code
              uses: actions/checkout@v4
              with:
                  persist-credentials: false
                  fetch-depth: 0
            - name: Update compose yaml
              uses: fjogeleit/yaml-update-action@v0.16.0
              with:
                  valueFile: compose.yaml
                  propertyPath: 'services["blog-server"].image'
                  value: ${{env.IMAGE_NAME}}:${{env.IMAGE_TAG}}
                  commitChange: false
            - name: Generate token
              id: generate_token
              uses: tibdex/github-app-token@v2
              with:
                  app_id: ${{secrets.APP_ID_GITHUB}}
                  private_key: ${{secrets.PRIVATE_KEY_GITHUB}}
            - name: Commit files
              run: |
                  git config --local user.name github-actions
                  git config --local user.email github-action@github.com
                  git add .
                  git commit -m "✨ shipped: new image ${{env.IMAGE_TAG}} [skip ci]"
            - name: Push changes
              uses: ad-m/github-push-action@master
              with:
                  github_token: ${{ steps.generate_token.outputs.token }}

            - name: Build docker image
              run: docker build -t ${{env.IMAGE_NAME}}:${{env.IMAGE_TAG}} --platform linux/amd64 .
            - name: Login into Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{secrets.DOCKERHUB_USERNAME}}
                  password: ${{secrets.DOCKERHUB_PASSWORD}}
            - name: Push docker image to Docker Hub
              run: docker push ${{env.IMAGE_NAME}}:${{env.IMAGE_TAG}}

    deploy:
        name: Deploy the image to Docker Swarm Cluster
        runs-on: ubuntu-latest
        env:
            IMAGE_NAME: runipanda/blog-app
            IMAGE_TAG: build-${{github.sha}}
        needs:
            - build-and-push
        steps:
            - name: SSH into the server
              uses: appleboy/ssh-action@v1
              with:
                  host: ${{secrets.SWARM_MAMAGER_HOST}}
                  username: ${{secrets.SWARM_MANAGER_USERNAME}}
                  key: ${{secrets.SWARM_MANAGER_SSH_KEY}}
                  port: ${{secrets.SWARM_MANAGER_PORT}}
                  script: |
                      set -e
                      cd ~/bloggy

                      # pull compose file using git
                      git fetch origin main
                      git checkout origin/main

                      docker pull ${{env.IMAGE_NAME}}:${{env.IMAGE_TAG}}
                      docker stack deploy -c compose.yaml bloggy